name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Сначала скачиваем код, потом ставим PHP!
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2 # Используй актуальную версию экшена
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, sqlite3 # Нужные расширения

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:" # Тесты в памяти работают в разы быстрее
      run: php artisan test

  deploy-server:
    runs-on: ubuntu-latest
    needs: [laravel-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Не деплоим из Pull Request!
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3 # Исправлено название
        with:
          host: 77.222.40.84
          username: 'soloimtech'
          key: ${{ secrets.SSH_KEY }} # Добавлены ${{ }}
          script: |
            cd /var/www/my-project
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
